import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This file defines the sidebars for your documentation

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated automatically from the filesystem, or defined manually here.
 * Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // Automatically generate sidebar from the docs folder
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Uncomment below to create manual sidebar
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
};

export default sidebars;
